### ISSUE TITLE
thumb placeholder position

### ISSUE THREAD

**Issue by EvaniRam** [lukelorusso/VerticalSeekBar#9]
Is there any way to adjust the **thumb** / slider position in between minimum and max of the **bar** .Currently thumb placeholder is center. 

val thumbHalfHeight = if (showThumb) thumb.measuredHeight / 2 else 0

**Comment by lukelorusso** [comment]
Sorry, I don't understand the question. Can you elaborate?
Consider that the thumb position depends on the progress value.

**Comment by EvaniRam** [comment]
Hi Lukelorusso,
  Thanks for the quick reply. My question is :
   When the thumb reaches max (100) or min (0) , the thumb image is slightly outside the bar.Is there any way to adjust the thumb position so that it would not cross the bar or stays in between the range of min and max.

![image](https://user-images.githubusercontent.com/6368710/79730796-fa479f00-830e-11ea-8ca0-d6b7ec1bceac.png)

![image](https://user-images.githubusercontent.com/6368710/79730843-12b7b980-830f-11ea-8ad1-f2ccf2ab50be.png)

**Comment by lukelorusso** [comment]
Ok I see your point. The simple answer is "it's not possible". But since yours it's more of a "graphical need" than a missing functionality lemme tell you what you can do:
you may define a max_placeholder and a min_placeholder, use the same resource as the one for your bar and play with their positions (inside/outside/middle). This way you can get the same graphical result using a different approach !
